package com.daniu.mybatis.dao;

import com.daniu.mybatis.model.BookLog;
import com.daniu.mybatis.model.BookLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_log
     *
     * @mbggenerated
     */
    int countByExample(BookLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_log
     *
     * @mbggenerated
     */
    int deleteByExample(BookLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_log
     *
     * @mbggenerated
     */
    int insert(BookLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_log
     *
     * @mbggenerated
     */
    int insertSelective(BookLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_log
     *
     * @mbggenerated
     */
    List<BookLog> selectByExample(BookLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_log
     *
     * @mbggenerated
     */
    BookLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BookLog record, @Param("example") BookLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BookLog record, @Param("example") BookLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BookLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BookLog record);
}