package com.daniu.mybatis.dao;

import com.daniu.mybatis.model.BookGroupInterest;
import com.daniu.mybatis.model.BookGroupInterestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookGroupInterestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_group_interest
     *
     * @mbggenerated
     */
    int countByExample(BookGroupInterestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_group_interest
     *
     * @mbggenerated
     */
    int deleteByExample(BookGroupInterestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_group_interest
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("groupId") Long groupId, @Param("userId") Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_group_interest
     *
     * @mbggenerated
     */
    int insert(BookGroupInterest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_group_interest
     *
     * @mbggenerated
     */
    int insertSelective(BookGroupInterest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_group_interest
     *
     * @mbggenerated
     */
    List<BookGroupInterest> selectByExample(BookGroupInterestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_group_interest
     *
     * @mbggenerated
     */
    BookGroupInterest selectByPrimaryKey(@Param("groupId") Long groupId, @Param("userId") Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_group_interest
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BookGroupInterest record, @Param("example") BookGroupInterestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_group_interest
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BookGroupInterest record, @Param("example") BookGroupInterestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_group_interest
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BookGroupInterest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_group_interest
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BookGroupInterest record);
}