package com.daniu.mybatis.dao;

import com.daniu.mybatis.model.CategoryItem;
import com.daniu.mybatis.model.CategoryItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoryItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_item
     *
     * @mbggenerated
     */
    int countByExample(CategoryItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_item
     *
     * @mbggenerated
     */
    int deleteByExample(CategoryItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_item
     *
     * @mbggenerated
     */
    int insert(CategoryItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_item
     *
     * @mbggenerated
     */
    int insertSelective(CategoryItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_item
     *
     * @mbggenerated
     */
    List<CategoryItem> selectByExample(CategoryItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_item
     *
     * @mbggenerated
     */
    CategoryItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_item
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CategoryItem record, @Param("example") CategoryItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_item
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CategoryItem record, @Param("example") CategoryItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CategoryItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CategoryItem record);
}