package com.daniu.mybatis.dao;

import com.daniu.mybatis.model.ChartItem;
import com.daniu.mybatis.model.ChartItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChartItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart_item
     *
     * @mbggenerated
     */
    int countByExample(ChartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart_item
     *
     * @mbggenerated
     */
    int deleteByExample(ChartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart_item
     *
     * @mbggenerated
     */
    int insert(ChartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart_item
     *
     * @mbggenerated
     */
    int insertSelective(ChartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart_item
     *
     * @mbggenerated
     */
    List<ChartItem> selectByExample(ChartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart_item
     *
     * @mbggenerated
     */
    ChartItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart_item
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ChartItem record, @Param("example") ChartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart_item
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ChartItem record, @Param("example") ChartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChartItem record);
}