package com.daniu.mybatis.dao;

import com.daniu.mybatis.model.Classfication;
import com.daniu.mybatis.model.ClassficationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassficationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classfication
     *
     * @mbggenerated
     */
    int countByExample(ClassficationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classfication
     *
     * @mbggenerated
     */
    int deleteByExample(ClassficationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classfication
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classfication
     *
     * @mbggenerated
     */
    int insert(Classfication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classfication
     *
     * @mbggenerated
     */
    int insertSelective(Classfication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classfication
     *
     * @mbggenerated
     */
    List<Classfication> selectByExample(ClassficationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classfication
     *
     * @mbggenerated
     */
    Classfication selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classfication
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Classfication record, @Param("example") ClassficationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classfication
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Classfication record, @Param("example") ClassficationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classfication
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Classfication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classfication
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Classfication record);
}