package com.daniu.mybatis.dao;

import com.daniu.mybatis.model.CmccContentProviderBook;
import com.daniu.mybatis.model.CmccContentProviderBookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmccContentProviderBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmcc_content_provider_book
     *
     * @mbggenerated
     */
    int countByExample(CmccContentProviderBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmcc_content_provider_book
     *
     * @mbggenerated
     */
    int deleteByExample(CmccContentProviderBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmcc_content_provider_book
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmcc_content_provider_book
     *
     * @mbggenerated
     */
    int insert(CmccContentProviderBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmcc_content_provider_book
     *
     * @mbggenerated
     */
    int insertSelective(CmccContentProviderBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmcc_content_provider_book
     *
     * @mbggenerated
     */
    List<CmccContentProviderBook> selectByExample(CmccContentProviderBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmcc_content_provider_book
     *
     * @mbggenerated
     */
    CmccContentProviderBook selectByPrimaryKey(Long bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmcc_content_provider_book
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CmccContentProviderBook record, @Param("example") CmccContentProviderBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmcc_content_provider_book
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CmccContentProviderBook record, @Param("example") CmccContentProviderBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmcc_content_provider_book
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CmccContentProviderBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmcc_content_provider_book
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CmccContentProviderBook record);
}