package com.daniu.mybatis.dao;

import com.daniu.mybatis.model.CpBookCategory;
import com.daniu.mybatis.model.CpBookCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CpBookCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_book_category
     *
     * @mbggenerated
     */
    int countByExample(CpBookCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_book_category
     *
     * @mbggenerated
     */
    int deleteByExample(CpBookCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_book_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String originName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_book_category
     *
     * @mbggenerated
     */
    int insert(CpBookCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_book_category
     *
     * @mbggenerated
     */
    int insertSelective(CpBookCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_book_category
     *
     * @mbggenerated
     */
    List<CpBookCategory> selectByExample(CpBookCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_book_category
     *
     * @mbggenerated
     */
    CpBookCategory selectByPrimaryKey(String originName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_book_category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CpBookCategory record, @Param("example") CpBookCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_book_category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CpBookCategory record, @Param("example") CpBookCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_book_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CpBookCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_book_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CpBookCategory record);
}