package com.daniu.mybatis.dao;

import com.daniu.mybatis.model.HelpContent;
import com.daniu.mybatis.model.HelpContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HelpContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_content
     *
     * @mbggenerated
     */
    int countByExample(HelpContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_content
     *
     * @mbggenerated
     */
    int deleteByExample(HelpContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_content
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_content
     *
     * @mbggenerated
     */
    int insert(HelpContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_content
     *
     * @mbggenerated
     */
    int insertSelective(HelpContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_content
     *
     * @mbggenerated
     */
    List<HelpContent> selectByExampleWithBLOBs(HelpContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_content
     *
     * @mbggenerated
     */
    List<HelpContent> selectByExample(HelpContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_content
     *
     * @mbggenerated
     */
    HelpContent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_content
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HelpContent record, @Param("example") HelpContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_content
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") HelpContent record, @Param("example") HelpContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_content
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HelpContent record, @Param("example") HelpContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HelpContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(HelpContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HelpContent record);
}