package com.daniu.mybatis.dao;

import com.daniu.mybatis.model.MemberExtra;
import com.daniu.mybatis.model.MemberExtraExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberExtraMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_extra
     *
     * @mbggenerated
     */
    int countByExample(MemberExtraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_extra
     *
     * @mbggenerated
     */
    int deleteByExample(MemberExtraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_extra
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_extra
     *
     * @mbggenerated
     */
    int insert(MemberExtra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_extra
     *
     * @mbggenerated
     */
    int insertSelective(MemberExtra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_extra
     *
     * @mbggenerated
     */
    List<MemberExtra> selectByExample(MemberExtraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_extra
     *
     * @mbggenerated
     */
    MemberExtra selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_extra
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MemberExtra record, @Param("example") MemberExtraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_extra
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MemberExtra record, @Param("example") MemberExtraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_extra
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemberExtra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_extra
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemberExtra record);
}