package com.daniu.mybatis.dao;

import com.daniu.mybatis.model.MonthlyPackageItem;
import com.daniu.mybatis.model.MonthlyPackageItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MonthlyPackageItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_package_item
     *
     * @mbggenerated
     */
    int countByExample(MonthlyPackageItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_package_item
     *
     * @mbggenerated
     */
    int deleteByExample(MonthlyPackageItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_package_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_package_item
     *
     * @mbggenerated
     */
    int insert(MonthlyPackageItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_package_item
     *
     * @mbggenerated
     */
    int insertSelective(MonthlyPackageItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_package_item
     *
     * @mbggenerated
     */
    List<MonthlyPackageItem> selectByExample(MonthlyPackageItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_package_item
     *
     * @mbggenerated
     */
    MonthlyPackageItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_package_item
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MonthlyPackageItem record, @Param("example") MonthlyPackageItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_package_item
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MonthlyPackageItem record, @Param("example") MonthlyPackageItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_package_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MonthlyPackageItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_package_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MonthlyPackageItem record);
}