package com.daniu.mybatis.dao;

import com.daniu.mybatis.model.MonthlyPackageCrawlerConfig;
import com.daniu.mybatis.model.MonthlyPackageCrawlerConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MonthlyPackageCrawlerConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_package_crawler_config
     *
     * @mbggenerated
     */
    int countByExample(MonthlyPackageCrawlerConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_package_crawler_config
     *
     * @mbggenerated
     */
    int deleteByExample(MonthlyPackageCrawlerConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_package_crawler_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long packageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_package_crawler_config
     *
     * @mbggenerated
     */
    int insert(MonthlyPackageCrawlerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_package_crawler_config
     *
     * @mbggenerated
     */
    int insertSelective(MonthlyPackageCrawlerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_package_crawler_config
     *
     * @mbggenerated
     */
    List<MonthlyPackageCrawlerConfig> selectByExample(MonthlyPackageCrawlerConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_package_crawler_config
     *
     * @mbggenerated
     */
    MonthlyPackageCrawlerConfig selectByPrimaryKey(Long packageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_package_crawler_config
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MonthlyPackageCrawlerConfig record, @Param("example") MonthlyPackageCrawlerConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_package_crawler_config
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MonthlyPackageCrawlerConfig record, @Param("example") MonthlyPackageCrawlerConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_package_crawler_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MonthlyPackageCrawlerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_package_crawler_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MonthlyPackageCrawlerConfig record);
}