package com.daniu.mybatis.dao;

import com.daniu.mybatis.model.ParttimerOperationAudit;
import com.daniu.mybatis.model.ParttimerOperationAuditExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ParttimerOperationAuditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parttimer_operation_audit
     *
     * @mbggenerated
     */
    int countByExample(ParttimerOperationAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parttimer_operation_audit
     *
     * @mbggenerated
     */
    int deleteByExample(ParttimerOperationAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parttimer_operation_audit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parttimer_operation_audit
     *
     * @mbggenerated
     */
    int insert(ParttimerOperationAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parttimer_operation_audit
     *
     * @mbggenerated
     */
    int insertSelective(ParttimerOperationAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parttimer_operation_audit
     *
     * @mbggenerated
     */
    List<ParttimerOperationAudit> selectByExample(ParttimerOperationAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parttimer_operation_audit
     *
     * @mbggenerated
     */
    ParttimerOperationAudit selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parttimer_operation_audit
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ParttimerOperationAudit record, @Param("example") ParttimerOperationAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parttimer_operation_audit
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ParttimerOperationAudit record, @Param("example") ParttimerOperationAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parttimer_operation_audit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ParttimerOperationAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parttimer_operation_audit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ParttimerOperationAudit record);
}