package com.daniu.mybatis.dao;

import com.daniu.mybatis.model.RankingCategory;
import com.daniu.mybatis.model.RankingCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RankingCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ranking_category
     *
     * @mbggenerated
     */
    int countByExample(RankingCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ranking_category
     *
     * @mbggenerated
     */
    int deleteByExample(RankingCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ranking_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ranking_category
     *
     * @mbggenerated
     */
    int insert(RankingCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ranking_category
     *
     * @mbggenerated
     */
    int insertSelective(RankingCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ranking_category
     *
     * @mbggenerated
     */
    List<RankingCategory> selectByExample(RankingCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ranking_category
     *
     * @mbggenerated
     */
    RankingCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ranking_category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RankingCategory record, @Param("example") RankingCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ranking_category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RankingCategory record, @Param("example") RankingCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ranking_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RankingCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ranking_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RankingCategory record);
}