package com.daniu.mybatis.dao;

import com.daniu.mybatis.model.RedeemCode;
import com.daniu.mybatis.model.RedeemCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RedeemCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redeem_code
     *
     * @mbggenerated
     */
    int countByExample(RedeemCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redeem_code
     *
     * @mbggenerated
     */
    int deleteByExample(RedeemCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redeem_code
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("code") String code, @Param("source") Integer source);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redeem_code
     *
     * @mbggenerated
     */
    int insert(RedeemCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redeem_code
     *
     * @mbggenerated
     */
    int insertSelective(RedeemCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redeem_code
     *
     * @mbggenerated
     */
    List<RedeemCode> selectByExample(RedeemCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redeem_code
     *
     * @mbggenerated
     */
    RedeemCode selectByPrimaryKey(@Param("code") String code, @Param("source") Integer source);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redeem_code
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RedeemCode record, @Param("example") RedeemCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redeem_code
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RedeemCode record, @Param("example") RedeemCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redeem_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RedeemCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redeem_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RedeemCode record);
}