package com.daniu.mybatis.dao;

import com.daniu.mybatis.model.SpecialSubjectStyleGroupCategory;
import com.daniu.mybatis.model.SpecialSubjectStyleGroupCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpecialSubjectStyleGroupCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group_category
     *
     * @mbggenerated
     */
    int countByExample(SpecialSubjectStyleGroupCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group_category
     *
     * @mbggenerated
     */
    int deleteByExample(SpecialSubjectStyleGroupCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group_category
     *
     * @mbggenerated
     */
    int insert(SpecialSubjectStyleGroupCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group_category
     *
     * @mbggenerated
     */
    int insertSelective(SpecialSubjectStyleGroupCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group_category
     *
     * @mbggenerated
     */
    List<SpecialSubjectStyleGroupCategory> selectByExample(SpecialSubjectStyleGroupCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group_category
     *
     * @mbggenerated
     */
    SpecialSubjectStyleGroupCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group_category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SpecialSubjectStyleGroupCategory record, @Param("example") SpecialSubjectStyleGroupCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group_category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SpecialSubjectStyleGroupCategory record, @Param("example") SpecialSubjectStyleGroupCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SpecialSubjectStyleGroupCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SpecialSubjectStyleGroupCategory record);
}