package com.daniu.mybatis.dao;

import com.daniu.mybatis.model.SpecialSubjectStyleGroupItem;
import com.daniu.mybatis.model.SpecialSubjectStyleGroupItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpecialSubjectStyleGroupItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group_item
     *
     * @mbggenerated
     */
    int countByExample(SpecialSubjectStyleGroupItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group_item
     *
     * @mbggenerated
     */
    int deleteByExample(SpecialSubjectStyleGroupItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group_item
     *
     * @mbggenerated
     */
    int insert(SpecialSubjectStyleGroupItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group_item
     *
     * @mbggenerated
     */
    int insertSelective(SpecialSubjectStyleGroupItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group_item
     *
     * @mbggenerated
     */
    List<SpecialSubjectStyleGroupItem> selectByExample(SpecialSubjectStyleGroupItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group_item
     *
     * @mbggenerated
     */
    SpecialSubjectStyleGroupItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group_item
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SpecialSubjectStyleGroupItem record, @Param("example") SpecialSubjectStyleGroupItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group_item
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SpecialSubjectStyleGroupItem record, @Param("example") SpecialSubjectStyleGroupItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SpecialSubjectStyleGroupItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SpecialSubjectStyleGroupItem record);
}