package com.daniu.mybatis.dao;

import com.daniu.mybatis.model.SpecialSubjectGroupItem;
import com.daniu.mybatis.model.SpecialSubjectGroupItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpecialSubjectGroupItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_group_item
     *
     * @mbggenerated
     */
    int countByExample(SpecialSubjectGroupItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_group_item
     *
     * @mbggenerated
     */
    int deleteByExample(SpecialSubjectGroupItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_group_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_group_item
     *
     * @mbggenerated
     */
    int insert(SpecialSubjectGroupItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_group_item
     *
     * @mbggenerated
     */
    int insertSelective(SpecialSubjectGroupItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_group_item
     *
     * @mbggenerated
     */
    List<SpecialSubjectGroupItem> selectByExample(SpecialSubjectGroupItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_group_item
     *
     * @mbggenerated
     */
    SpecialSubjectGroupItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_group_item
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SpecialSubjectGroupItem record, @Param("example") SpecialSubjectGroupItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_group_item
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SpecialSubjectGroupItem record, @Param("example") SpecialSubjectGroupItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_group_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SpecialSubjectGroupItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_group_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SpecialSubjectGroupItem record);
}