package com.daniu.mybatis.dao;

import com.daniu.mybatis.model.SpecialSubjectStyleGroup;
import com.daniu.mybatis.model.SpecialSubjectStyleGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpecialSubjectStyleGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group
     *
     * @mbggenerated
     */
    int countByExample(SpecialSubjectStyleGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group
     *
     * @mbggenerated
     */
    int deleteByExample(SpecialSubjectStyleGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group
     *
     * @mbggenerated
     */
    int insert(SpecialSubjectStyleGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group
     *
     * @mbggenerated
     */
    int insertSelective(SpecialSubjectStyleGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group
     *
     * @mbggenerated
     */
    List<SpecialSubjectStyleGroup> selectByExample(SpecialSubjectStyleGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group
     *
     * @mbggenerated
     */
    SpecialSubjectStyleGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SpecialSubjectStyleGroup record, @Param("example") SpecialSubjectStyleGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SpecialSubjectStyleGroup record, @Param("example") SpecialSubjectStyleGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SpecialSubjectStyleGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_style_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SpecialSubjectStyleGroup record);
}