package com.daniu.mybatis.dao;

import com.daniu.mybatis.model.SynthesizeRecommendBook;
import com.daniu.mybatis.model.SynthesizeRecommendBookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SynthesizeRecommendBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_book
     *
     * @mbggenerated
     */
    int countByExample(SynthesizeRecommendBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_book
     *
     * @mbggenerated
     */
    int deleteByExample(SynthesizeRecommendBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_book
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("bid") Long bid, @Param("recommendId") Long recommendId, @Param("type") Byte type);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_book
     *
     * @mbggenerated
     */
    int insert(SynthesizeRecommendBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_book
     *
     * @mbggenerated
     */
    int insertSelective(SynthesizeRecommendBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_book
     *
     * @mbggenerated
     */
    List<SynthesizeRecommendBook> selectByExample(SynthesizeRecommendBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_book
     *
     * @mbggenerated
     */
    SynthesizeRecommendBook selectByPrimaryKey(@Param("bid") Long bid, @Param("recommendId") Long recommendId, @Param("type") Byte type);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_book
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SynthesizeRecommendBook record, @Param("example") SynthesizeRecommendBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_book
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SynthesizeRecommendBook record, @Param("example") SynthesizeRecommendBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_book
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SynthesizeRecommendBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_book
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SynthesizeRecommendBook record);
}