package com.daniu.mybatis.dao;

import com.daniu.mybatis.model.SynthesizeRecommendClassification;
import com.daniu.mybatis.model.SynthesizeRecommendClassificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SynthesizeRecommendClassificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_classification
     *
     * @mbggenerated
     */
    int countByExample(SynthesizeRecommendClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_classification
     *
     * @mbggenerated
     */
    int deleteByExample(SynthesizeRecommendClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_classification
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_classification
     *
     * @mbggenerated
     */
    int insert(SynthesizeRecommendClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_classification
     *
     * @mbggenerated
     */
    int insertSelective(SynthesizeRecommendClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_classification
     *
     * @mbggenerated
     */
    List<SynthesizeRecommendClassification> selectByExample(SynthesizeRecommendClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_classification
     *
     * @mbggenerated
     */
    SynthesizeRecommendClassification selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_classification
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SynthesizeRecommendClassification record, @Param("example") SynthesizeRecommendClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_classification
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SynthesizeRecommendClassification record, @Param("example") SynthesizeRecommendClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_classification
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SynthesizeRecommendClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_classification
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SynthesizeRecommendClassification record);
}