package com.daniu.mybatis.dao;

import com.daniu.mybatis.model.SynthesizeRecommendType;
import com.daniu.mybatis.model.SynthesizeRecommendTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SynthesizeRecommendTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_type
     *
     * @mbggenerated
     */
    int countByExample(SynthesizeRecommendTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_type
     *
     * @mbggenerated
     */
    int deleteByExample(SynthesizeRecommendTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_type
     *
     * @mbggenerated
     */
    int insert(SynthesizeRecommendType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_type
     *
     * @mbggenerated
     */
    int insertSelective(SynthesizeRecommendType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_type
     *
     * @mbggenerated
     */
    List<SynthesizeRecommendType> selectByExample(SynthesizeRecommendTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_type
     *
     * @mbggenerated
     */
    SynthesizeRecommendType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SynthesizeRecommendType record, @Param("example") SynthesizeRecommendTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SynthesizeRecommendType record, @Param("example") SynthesizeRecommendTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SynthesizeRecommendType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synthesize_recommend_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SynthesizeRecommendType record);
}