package com.daniu.mybatis.dao;

import com.daniu.mybatis.model.UserPointReportLog;
import com.daniu.mybatis.model.UserPointReportLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPointReportLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point_report_log
     *
     * @mbggenerated
     */
    int countByExample(UserPointReportLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point_report_log
     *
     * @mbggenerated
     */
    int deleteByExample(UserPointReportLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point_report_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("timestamp") Long timestamp, @Param("userId") Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point_report_log
     *
     * @mbggenerated
     */
    int insert(UserPointReportLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point_report_log
     *
     * @mbggenerated
     */
    int insertSelective(UserPointReportLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point_report_log
     *
     * @mbggenerated
     */
    List<UserPointReportLog> selectByExample(UserPointReportLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point_report_log
     *
     * @mbggenerated
     */
    UserPointReportLog selectByPrimaryKey(@Param("timestamp") Long timestamp, @Param("userId") Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point_report_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserPointReportLog record, @Param("example") UserPointReportLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point_report_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserPointReportLog record, @Param("example") UserPointReportLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point_report_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserPointReportLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point_report_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserPointReportLog record);
}