package com.daniu.mybatis.dao;

import com.daniu.mybatis.model.Volumn;
import com.daniu.mybatis.model.VolumnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VolumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volumn
     *
     * @mbggenerated
     */
    int countByExample(VolumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volumn
     *
     * @mbggenerated
     */
    int deleteByExample(VolumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volumn
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volumn
     *
     * @mbggenerated
     */
    int insert(Volumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volumn
     *
     * @mbggenerated
     */
    int insertSelective(Volumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volumn
     *
     * @mbggenerated
     */
    List<Volumn> selectByExample(VolumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volumn
     *
     * @mbggenerated
     */
    Volumn selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volumn
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Volumn record, @Param("example") VolumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volumn
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Volumn record, @Param("example") VolumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volumn
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Volumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volumn
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Volumn record);
}