package com.daniu.mybatis.dao;

import com.daniu.mybatis.model.WebAppskins;
import com.daniu.mybatis.model.WebAppskinsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebAppskinsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_appskins
     *
     * @mbggenerated
     */
    int countByExample(WebAppskinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_appskins
     *
     * @mbggenerated
     */
    int deleteByExample(WebAppskinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_appskins
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_appskins
     *
     * @mbggenerated
     */
    int insert(WebAppskins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_appskins
     *
     * @mbggenerated
     */
    int insertSelective(WebAppskins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_appskins
     *
     * @mbggenerated
     */
    List<WebAppskins> selectByExample(WebAppskinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_appskins
     *
     * @mbggenerated
     */
    WebAppskins selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_appskins
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WebAppskins record, @Param("example") WebAppskinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_appskins
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WebAppskins record, @Param("example") WebAppskinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_appskins
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WebAppskins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_appskins
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WebAppskins record);
}