package com.daniu.mybatis.model;

import java.util.Date;

public class AlbumInterest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album_interest.album_id
     *
     * @mbggenerated
     */
    private Long albumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album_interest.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album_interest.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album_interest.collect
     *
     * @mbggenerated
     */
    private Byte collect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album_interest.vote
     *
     * @mbggenerated
     */
    private Byte vote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album_interest.album_id
     *
     * @return the value of album_interest.album_id
     *
     * @mbggenerated
     */
    public Long getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album_interest.album_id
     *
     * @param albumId the value for album_interest.album_id
     *
     * @mbggenerated
     */
    public void setAlbumId(Long albumId) {
        this.albumId = albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album_interest.user_id
     *
     * @return the value of album_interest.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album_interest.user_id
     *
     * @param userId the value for album_interest.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album_interest.create_time
     *
     * @return the value of album_interest.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album_interest.create_time
     *
     * @param createTime the value for album_interest.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album_interest.collect
     *
     * @return the value of album_interest.collect
     *
     * @mbggenerated
     */
    public Byte getCollect() {
        return collect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album_interest.collect
     *
     * @param collect the value for album_interest.collect
     *
     * @mbggenerated
     */
    public void setCollect(Byte collect) {
        this.collect = collect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album_interest.vote
     *
     * @return the value of album_interest.vote
     *
     * @mbggenerated
     */
    public Byte getVote() {
        return vote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album_interest.vote
     *
     * @param vote the value for album_interest.vote
     *
     * @mbggenerated
     */
    public void setVote(Byte vote) {
        this.vote = vote;
    }
}