package com.daniu.mybatis.model;

import java.util.Date;

public class BookShare {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.book_name
     *
     * @mbggenerated
     */
    private String bookName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.category
     *
     * @mbggenerated
     */
    private Long category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.size
     *
     * @mbggenerated
     */
    private Long size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.fine
     *
     * @mbggenerated
     */
    private Integer fine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.format
     *
     * @mbggenerated
     */
    private String format;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.begin_time
     *
     * @mbggenerated
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.tags
     *
     * @mbggenerated
     */
    private String tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.word_count
     *
     * @mbggenerated
     */
    private String wordCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.essence
     *
     * @mbggenerated
     */
    private Integer essence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.recommends
     *
     * @mbggenerated
     */
    private String recommends;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.download_count
     *
     * @mbggenerated
     */
    private Integer downloadCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.book_id
     *
     * @mbggenerated
     */
    private Long bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.source
     *
     * @mbggenerated
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.last_comment
     *
     * @mbggenerated
     */
    private Date lastComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.comment_count
     *
     * @mbggenerated
     */
    private Integer commentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_share.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.id
     *
     * @return the value of book_share.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.id
     *
     * @param id the value for book_share.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.book_name
     *
     * @return the value of book_share.book_name
     *
     * @mbggenerated
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.book_name
     *
     * @param bookName the value for book_share.book_name
     *
     * @mbggenerated
     */
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.category
     *
     * @return the value of book_share.category
     *
     * @mbggenerated
     */
    public Long getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.category
     *
     * @param category the value for book_share.category
     *
     * @mbggenerated
     */
    public void setCategory(Long category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.description
     *
     * @return the value of book_share.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.description
     *
     * @param description the value for book_share.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.size
     *
     * @return the value of book_share.size
     *
     * @mbggenerated
     */
    public Long getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.size
     *
     * @param size the value for book_share.size
     *
     * @mbggenerated
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.fine
     *
     * @return the value of book_share.fine
     *
     * @mbggenerated
     */
    public Integer getFine() {
        return fine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.fine
     *
     * @param fine the value for book_share.fine
     *
     * @mbggenerated
     */
    public void setFine(Integer fine) {
        this.fine = fine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.url
     *
     * @return the value of book_share.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.url
     *
     * @param url the value for book_share.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.format
     *
     * @return the value of book_share.format
     *
     * @mbggenerated
     */
    public String getFormat() {
        return format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.format
     *
     * @param format the value for book_share.format
     *
     * @mbggenerated
     */
    public void setFormat(String format) {
        this.format = format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.path
     *
     * @return the value of book_share.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.path
     *
     * @param path the value for book_share.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.user_id
     *
     * @return the value of book_share.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.user_id
     *
     * @param userId the value for book_share.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.begin_time
     *
     * @return the value of book_share.begin_time
     *
     * @mbggenerated
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.begin_time
     *
     * @param beginTime the value for book_share.begin_time
     *
     * @mbggenerated
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.end_time
     *
     * @return the value of book_share.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.end_time
     *
     * @param endTime the value for book_share.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.author
     *
     * @return the value of book_share.author
     *
     * @mbggenerated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.author
     *
     * @param author the value for book_share.author
     *
     * @mbggenerated
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.tags
     *
     * @return the value of book_share.tags
     *
     * @mbggenerated
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.tags
     *
     * @param tags the value for book_share.tags
     *
     * @mbggenerated
     */
    public void setTags(String tags) {
        this.tags = tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.state
     *
     * @return the value of book_share.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.state
     *
     * @param state the value for book_share.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.word_count
     *
     * @return the value of book_share.word_count
     *
     * @mbggenerated
     */
    public String getWordCount() {
        return wordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.word_count
     *
     * @param wordCount the value for book_share.word_count
     *
     * @mbggenerated
     */
    public void setWordCount(String wordCount) {
        this.wordCount = wordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.essence
     *
     * @return the value of book_share.essence
     *
     * @mbggenerated
     */
    public Integer getEssence() {
        return essence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.essence
     *
     * @param essence the value for book_share.essence
     *
     * @mbggenerated
     */
    public void setEssence(Integer essence) {
        this.essence = essence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.score
     *
     * @return the value of book_share.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.score
     *
     * @param score the value for book_share.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.recommends
     *
     * @return the value of book_share.recommends
     *
     * @mbggenerated
     */
    public String getRecommends() {
        return recommends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.recommends
     *
     * @param recommends the value for book_share.recommends
     *
     * @mbggenerated
     */
    public void setRecommends(String recommends) {
        this.recommends = recommends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.download_count
     *
     * @return the value of book_share.download_count
     *
     * @mbggenerated
     */
    public Integer getDownloadCount() {
        return downloadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.download_count
     *
     * @param downloadCount the value for book_share.download_count
     *
     * @mbggenerated
     */
    public void setDownloadCount(Integer downloadCount) {
        this.downloadCount = downloadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.book_id
     *
     * @return the value of book_share.book_id
     *
     * @mbggenerated
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.book_id
     *
     * @param bookId the value for book_share.book_id
     *
     * @mbggenerated
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.source
     *
     * @return the value of book_share.source
     *
     * @mbggenerated
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.source
     *
     * @param source the value for book_share.source
     *
     * @mbggenerated
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.last_comment
     *
     * @return the value of book_share.last_comment
     *
     * @mbggenerated
     */
    public Date getLastComment() {
        return lastComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.last_comment
     *
     * @param lastComment the value for book_share.last_comment
     *
     * @mbggenerated
     */
    public void setLastComment(Date lastComment) {
        this.lastComment = lastComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.comment_count
     *
     * @return the value of book_share.comment_count
     *
     * @mbggenerated
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.comment_count
     *
     * @param commentCount the value for book_share.comment_count
     *
     * @mbggenerated
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_share.create_time
     *
     * @return the value of book_share.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_share.create_time
     *
     * @param createTime the value for book_share.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}