package com.daniu.mybatis.model;

public class BookRecommendContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_recommend_content.bid
     *
     * @mbggenerated
     */
    private Long bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_recommend_content.valid_day
     *
     * @mbggenerated
     */
    private Integer validDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_recommend_content.valid_value
     *
     * @mbggenerated
     */
    private String validValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_recommend_content.content_type
     *
     * @mbggenerated
     */
    private Integer contentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_recommend_content.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_recommend_content.source
     *
     * @mbggenerated
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_recommend_content.contents
     *
     * @mbggenerated
     */
    private String contents;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_recommend_content.bid
     *
     * @return the value of book_recommend_content.bid
     *
     * @mbggenerated
     */
    public Long getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_recommend_content.bid
     *
     * @param bid the value for book_recommend_content.bid
     *
     * @mbggenerated
     */
    public void setBid(Long bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_recommend_content.valid_day
     *
     * @return the value of book_recommend_content.valid_day
     *
     * @mbggenerated
     */
    public Integer getValidDay() {
        return validDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_recommend_content.valid_day
     *
     * @param validDay the value for book_recommend_content.valid_day
     *
     * @mbggenerated
     */
    public void setValidDay(Integer validDay) {
        this.validDay = validDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_recommend_content.valid_value
     *
     * @return the value of book_recommend_content.valid_value
     *
     * @mbggenerated
     */
    public String getValidValue() {
        return validValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_recommend_content.valid_value
     *
     * @param validValue the value for book_recommend_content.valid_value
     *
     * @mbggenerated
     */
    public void setValidValue(String validValue) {
        this.validValue = validValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_recommend_content.content_type
     *
     * @return the value of book_recommend_content.content_type
     *
     * @mbggenerated
     */
    public Integer getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_recommend_content.content_type
     *
     * @param contentType the value for book_recommend_content.content_type
     *
     * @mbggenerated
     */
    public void setContentType(Integer contentType) {
        this.contentType = contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_recommend_content.type
     *
     * @return the value of book_recommend_content.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_recommend_content.type
     *
     * @param type the value for book_recommend_content.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_recommend_content.source
     *
     * @return the value of book_recommend_content.source
     *
     * @mbggenerated
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_recommend_content.source
     *
     * @param source the value for book_recommend_content.source
     *
     * @mbggenerated
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_recommend_content.contents
     *
     * @return the value of book_recommend_content.contents
     *
     * @mbggenerated
     */
    public String getContents() {
        return contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_recommend_content.contents
     *
     * @param contents the value for book_recommend_content.contents
     *
     * @mbggenerated
     */
    public void setContents(String contents) {
        this.contents = contents;
    }
}