package com.daniu.mybatis.model;

import java.util.Date;

public class BookOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_order.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_order.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_order.book_id
     *
     * @mbggenerated
     */
    private Long bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_order.chapter_id
     *
     * @mbggenerated
     */
    private Long chapterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_order.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_order.price
     *
     * @mbggenerated
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_order.coupon
     *
     * @mbggenerated
     */
    private Long coupon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_order.grants
     *
     * @mbggenerated
     */
    private Long grants;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_order.activity
     *
     * @mbggenerated
     */
    private String activity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_order.id
     *
     * @return the value of book_order.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_order.id
     *
     * @param id the value for book_order.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_order.user_id
     *
     * @return the value of book_order.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_order.user_id
     *
     * @param userId the value for book_order.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_order.book_id
     *
     * @return the value of book_order.book_id
     *
     * @mbggenerated
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_order.book_id
     *
     * @param bookId the value for book_order.book_id
     *
     * @mbggenerated
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_order.chapter_id
     *
     * @return the value of book_order.chapter_id
     *
     * @mbggenerated
     */
    public Long getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_order.chapter_id
     *
     * @param chapterId the value for book_order.chapter_id
     *
     * @mbggenerated
     */
    public void setChapterId(Long chapterId) {
        this.chapterId = chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_order.create_time
     *
     * @return the value of book_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_order.create_time
     *
     * @param createTime the value for book_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_order.price
     *
     * @return the value of book_order.price
     *
     * @mbggenerated
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_order.price
     *
     * @param price the value for book_order.price
     *
     * @mbggenerated
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_order.coupon
     *
     * @return the value of book_order.coupon
     *
     * @mbggenerated
     */
    public Long getCoupon() {
        return coupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_order.coupon
     *
     * @param coupon the value for book_order.coupon
     *
     * @mbggenerated
     */
    public void setCoupon(Long coupon) {
        this.coupon = coupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_order.grants
     *
     * @return the value of book_order.grants
     *
     * @mbggenerated
     */
    public Long getGrants() {
        return grants;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_order.grants
     *
     * @param grants the value for book_order.grants
     *
     * @mbggenerated
     */
    public void setGrants(Long grants) {
        this.grants = grants;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_order.activity
     *
     * @return the value of book_order.activity
     *
     * @mbggenerated
     */
    public String getActivity() {
        return activity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_order.activity
     *
     * @param activity the value for book_order.activity
     *
     * @mbggenerated
     */
    public void setActivity(String activity) {
        this.activity = activity;
    }
}