package com.daniu.mybatis.model;

public class QuestAction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_action.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_action.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_action.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_action.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_action.need_receive
     *
     * @mbggenerated
     */
    private Integer needReceive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_action.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_action.id
     *
     * @return the value of quest_action.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_action.id
     *
     * @param id the value for quest_action.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_action.name
     *
     * @return the value of quest_action.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_action.name
     *
     * @param name the value for quest_action.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_action.url
     *
     * @return the value of quest_action.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_action.url
     *
     * @param url the value for quest_action.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_action.description
     *
     * @return the value of quest_action.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_action.description
     *
     * @param description the value for quest_action.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_action.need_receive
     *
     * @return the value of quest_action.need_receive
     *
     * @mbggenerated
     */
    public Integer getNeedReceive() {
        return needReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_action.need_receive
     *
     * @param needReceive the value for quest_action.need_receive
     *
     * @mbggenerated
     */
    public void setNeedReceive(Integer needReceive) {
        this.needReceive = needReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_action.version
     *
     * @return the value of quest_action.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_action.version
     *
     * @param version the value for quest_action.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}