package com.daniu.mybatis.model;

import java.util.Date;

public class QuestLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_log.quest_id
     *
     * @mbggenerated
     */
    private Long questId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_log.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_log.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_log.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_log.quest_name
     *
     * @mbggenerated
     */
    private String questName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_log.unread
     *
     * @mbggenerated
     */
    private Integer unread;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_log.grants
     *
     * @mbggenerated
     */
    private Integer grants;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_log.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_log.finish_time
     *
     * @mbggenerated
     */
    private Date finishTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_log.id
     *
     * @return the value of quest_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_log.id
     *
     * @param id the value for quest_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_log.quest_id
     *
     * @return the value of quest_log.quest_id
     *
     * @mbggenerated
     */
    public Long getQuestId() {
        return questId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_log.quest_id
     *
     * @param questId the value for quest_log.quest_id
     *
     * @mbggenerated
     */
    public void setQuestId(Long questId) {
        this.questId = questId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_log.user_id
     *
     * @return the value of quest_log.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_log.user_id
     *
     * @param userId the value for quest_log.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_log.state
     *
     * @return the value of quest_log.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_log.state
     *
     * @param state the value for quest_log.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_log.create_time
     *
     * @return the value of quest_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_log.create_time
     *
     * @param createTime the value for quest_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_log.quest_name
     *
     * @return the value of quest_log.quest_name
     *
     * @mbggenerated
     */
    public String getQuestName() {
        return questName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_log.quest_name
     *
     * @param questName the value for quest_log.quest_name
     *
     * @mbggenerated
     */
    public void setQuestName(String questName) {
        this.questName = questName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_log.unread
     *
     * @return the value of quest_log.unread
     *
     * @mbggenerated
     */
    public Integer getUnread() {
        return unread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_log.unread
     *
     * @param unread the value for quest_log.unread
     *
     * @mbggenerated
     */
    public void setUnread(Integer unread) {
        this.unread = unread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_log.grants
     *
     * @return the value of quest_log.grants
     *
     * @mbggenerated
     */
    public Integer getGrants() {
        return grants;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_log.grants
     *
     * @param grants the value for quest_log.grants
     *
     * @mbggenerated
     */
    public void setGrants(Integer grants) {
        this.grants = grants;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_log.count
     *
     * @return the value of quest_log.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_log.count
     *
     * @param count the value for quest_log.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_log.finish_time
     *
     * @return the value of quest_log.finish_time
     *
     * @mbggenerated
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_log.finish_time
     *
     * @param finishTime the value for quest_log.finish_time
     *
     * @mbggenerated
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }
}