package com.daniu.mybatis.model;

public class RolePermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.perm_actions
     *
     * @mbggenerated
     */
    private String permActions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.perm_domain
     *
     * @mbggenerated
     */
    private String permDomain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.perm_targets
     *
     * @mbggenerated
     */
    private String permTargets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.role_id
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.perm_actions
     *
     * @return the value of role_permission.perm_actions
     *
     * @mbggenerated
     */
    public String getPermActions() {
        return permActions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.perm_actions
     *
     * @param permActions the value for role_permission.perm_actions
     *
     * @mbggenerated
     */
    public void setPermActions(String permActions) {
        this.permActions = permActions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.perm_domain
     *
     * @return the value of role_permission.perm_domain
     *
     * @mbggenerated
     */
    public String getPermDomain() {
        return permDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.perm_domain
     *
     * @param permDomain the value for role_permission.perm_domain
     *
     * @mbggenerated
     */
    public void setPermDomain(String permDomain) {
        this.permDomain = permDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.perm_targets
     *
     * @return the value of role_permission.perm_targets
     *
     * @mbggenerated
     */
    public String getPermTargets() {
        return permTargets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.perm_targets
     *
     * @param permTargets the value for role_permission.perm_targets
     *
     * @mbggenerated
     */
    public void setPermTargets(String permTargets) {
        this.permTargets = permTargets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.role_id
     *
     * @return the value of role_permission.role_id
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.role_id
     *
     * @param roleId the value for role_permission.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}