package com.daniu.mybatis.model;

public class RoleModule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_module.moduleId
     *
     * @mbggenerated
     */
    private Long moduleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_module.roleId
     *
     * @mbggenerated
     */
    private Long roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_module.moduleId
     *
     * @return the value of role_module.moduleId
     *
     * @mbggenerated
     */
    public Long getModuleid() {
        return moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_module.moduleId
     *
     * @param moduleid the value for role_module.moduleId
     *
     * @mbggenerated
     */
    public void setModuleid(Long moduleid) {
        this.moduleid = moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_module.roleId
     *
     * @return the value of role_module.roleId
     *
     * @mbggenerated
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_module.roleId
     *
     * @param roleid the value for role_module.roleId
     *
     * @mbggenerated
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }
}