package com.daniu.mybatis.model;

public class ShelfRecommendBook {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shelf_recommend_book.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shelf_recommend_book.bid
     *
     * @mbggenerated
     */
    private Long bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shelf_recommend_book.bookstore
     *
     * @mbggenerated
     */
    private Short bookstore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shelf_recommend_book.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shelf_recommend_book.book_id
     *
     * @mbggenerated
     */
    private Long bookId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shelf_recommend_book.id
     *
     * @return the value of shelf_recommend_book.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shelf_recommend_book.id
     *
     * @param id the value for shelf_recommend_book.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shelf_recommend_book.bid
     *
     * @return the value of shelf_recommend_book.bid
     *
     * @mbggenerated
     */
    public Long getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shelf_recommend_book.bid
     *
     * @param bid the value for shelf_recommend_book.bid
     *
     * @mbggenerated
     */
    public void setBid(Long bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shelf_recommend_book.bookstore
     *
     * @return the value of shelf_recommend_book.bookstore
     *
     * @mbggenerated
     */
    public Short getBookstore() {
        return bookstore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shelf_recommend_book.bookstore
     *
     * @param bookstore the value for shelf_recommend_book.bookstore
     *
     * @mbggenerated
     */
    public void setBookstore(Short bookstore) {
        this.bookstore = bookstore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shelf_recommend_book.type
     *
     * @return the value of shelf_recommend_book.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shelf_recommend_book.type
     *
     * @param type the value for shelf_recommend_book.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shelf_recommend_book.book_id
     *
     * @return the value of shelf_recommend_book.book_id
     *
     * @mbggenerated
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shelf_recommend_book.book_id
     *
     * @param bookId the value for shelf_recommend_book.book_id
     *
     * @mbggenerated
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }
}