package com.daniu.mybatis.model;

public class SpecialSubjectGroupItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_subject_group_item.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_subject_group_item.group_id
     *
     * @mbggenerated
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_subject_group_item.subject_id
     *
     * @mbggenerated
     */
    private Long subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_subject_group_item.order
     *
     * @mbggenerated
     */
    private Integer order;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_subject_group_item.id
     *
     * @return the value of special_subject_group_item.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_subject_group_item.id
     *
     * @param id the value for special_subject_group_item.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_subject_group_item.group_id
     *
     * @return the value of special_subject_group_item.group_id
     *
     * @mbggenerated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_subject_group_item.group_id
     *
     * @param groupId the value for special_subject_group_item.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_subject_group_item.subject_id
     *
     * @return the value of special_subject_group_item.subject_id
     *
     * @mbggenerated
     */
    public Long getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_subject_group_item.subject_id
     *
     * @param subjectId the value for special_subject_group_item.subject_id
     *
     * @mbggenerated
     */
    public void setSubjectId(Long subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_subject_group_item.order
     *
     * @return the value of special_subject_group_item.order
     *
     * @mbggenerated
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_subject_group_item.order
     *
     * @param order the value for special_subject_group_item.order
     *
     * @mbggenerated
     */
    public void setOrder(Integer order) {
        this.order = order;
    }
}