package com.daniu.mybatis.model;

import java.util.Date;

public class SubjectTagCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_tag_category.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_tag_category.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_tag_category.order
     *
     * @mbggenerated
     */
    private Integer order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_tag_category.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_tag_category.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_tag_category.position
     *
     * @mbggenerated
     */
    private Integer position;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_tag_category.id
     *
     * @return the value of subject_tag_category.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_tag_category.id
     *
     * @param id the value for subject_tag_category.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_tag_category.name
     *
     * @return the value of subject_tag_category.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_tag_category.name
     *
     * @param name the value for subject_tag_category.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_tag_category.order
     *
     * @return the value of subject_tag_category.order
     *
     * @mbggenerated
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_tag_category.order
     *
     * @param order the value for subject_tag_category.order
     *
     * @mbggenerated
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_tag_category.remark
     *
     * @return the value of subject_tag_category.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_tag_category.remark
     *
     * @param remark the value for subject_tag_category.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_tag_category.create_time
     *
     * @return the value of subject_tag_category.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_tag_category.create_time
     *
     * @param createTime the value for subject_tag_category.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_tag_category.position
     *
     * @return the value of subject_tag_category.position
     *
     * @mbggenerated
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_tag_category.position
     *
     * @param position the value for subject_tag_category.position
     *
     * @mbggenerated
     */
    public void setPosition(Integer position) {
        this.position = position;
    }
}