package com.daniu.mybatis.model;

import java.util.Date;

public class TitleRanking {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title_ranking.bid
     *
     * @mbggenerated
     */
    private Long bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title_ranking.custom_type
     *
     * @mbggenerated
     */
    private Integer customType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title_ranking.title_type
     *
     * @mbggenerated
     */
    private Integer titleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title_ranking.ranking
     *
     * @mbggenerated
     */
    private Integer ranking;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title_ranking.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title_ranking.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title_ranking.sub_title
     *
     * @mbggenerated
     */
    private String subTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title_ranking.source
     *
     * @mbggenerated
     */
    private Integer source;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title_ranking.bid
     *
     * @return the value of title_ranking.bid
     *
     * @mbggenerated
     */
    public Long getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title_ranking.bid
     *
     * @param bid the value for title_ranking.bid
     *
     * @mbggenerated
     */
    public void setBid(Long bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title_ranking.custom_type
     *
     * @return the value of title_ranking.custom_type
     *
     * @mbggenerated
     */
    public Integer getCustomType() {
        return customType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title_ranking.custom_type
     *
     * @param customType the value for title_ranking.custom_type
     *
     * @mbggenerated
     */
    public void setCustomType(Integer customType) {
        this.customType = customType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title_ranking.title_type
     *
     * @return the value of title_ranking.title_type
     *
     * @mbggenerated
     */
    public Integer getTitleType() {
        return titleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title_ranking.title_type
     *
     * @param titleType the value for title_ranking.title_type
     *
     * @mbggenerated
     */
    public void setTitleType(Integer titleType) {
        this.titleType = titleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title_ranking.ranking
     *
     * @return the value of title_ranking.ranking
     *
     * @mbggenerated
     */
    public Integer getRanking() {
        return ranking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title_ranking.ranking
     *
     * @param ranking the value for title_ranking.ranking
     *
     * @mbggenerated
     */
    public void setRanking(Integer ranking) {
        this.ranking = ranking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title_ranking.create_time
     *
     * @return the value of title_ranking.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title_ranking.create_time
     *
     * @param createTime the value for title_ranking.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title_ranking.update_time
     *
     * @return the value of title_ranking.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title_ranking.update_time
     *
     * @param updateTime the value for title_ranking.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title_ranking.sub_title
     *
     * @return the value of title_ranking.sub_title
     *
     * @mbggenerated
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title_ranking.sub_title
     *
     * @param subTitle the value for title_ranking.sub_title
     *
     * @mbggenerated
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title_ranking.source
     *
     * @return the value of title_ranking.source
     *
     * @mbggenerated
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title_ranking.source
     *
     * @param source the value for title_ranking.source
     *
     * @mbggenerated
     */
    public void setSource(Integer source) {
        this.source = source;
    }
}