package com.daniu.mybatis.model;

public class UserAlbumItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_album_item.album_id
     *
     * @mbggenerated
     */
    private Long albumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_album_item.book_id
     *
     * @mbggenerated
     */
    private Long bookId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_album_item.album_id
     *
     * @return the value of user_album_item.album_id
     *
     * @mbggenerated
     */
    public Long getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_album_item.album_id
     *
     * @param albumId the value for user_album_item.album_id
     *
     * @mbggenerated
     */
    public void setAlbumId(Long albumId) {
        this.albumId = albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_album_item.book_id
     *
     * @return the value of user_album_item.book_id
     *
     * @mbggenerated
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_album_item.book_id
     *
     * @param bookId the value for user_album_item.book_id
     *
     * @mbggenerated
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }
}