package com.daniu.mybatis.model;

public class UserDeviceLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device_log.target_id
     *
     * @mbggenerated
     */
    private Long targetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device_log.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device_log.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device_log.model
     *
     * @mbggenerated
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device_log.platform
     *
     * @mbggenerated
     */
    private String platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device_log.os
     *
     * @mbggenerated
     */
    private String os;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device_log.device
     *
     * @mbggenerated
     */
    private String device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device_log.ip
     *
     * @mbggenerated
     */
    private Long ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device_log.channel
     *
     * @mbggenerated
     */
    private String channel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device_log.id
     *
     * @return the value of user_device_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device_log.id
     *
     * @param id the value for user_device_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device_log.target_id
     *
     * @return the value of user_device_log.target_id
     *
     * @mbggenerated
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device_log.target_id
     *
     * @param targetId the value for user_device_log.target_id
     *
     * @mbggenerated
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device_log.type
     *
     * @return the value of user_device_log.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device_log.type
     *
     * @param type the value for user_device_log.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device_log.version
     *
     * @return the value of user_device_log.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device_log.version
     *
     * @param version the value for user_device_log.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device_log.model
     *
     * @return the value of user_device_log.model
     *
     * @mbggenerated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device_log.model
     *
     * @param model the value for user_device_log.model
     *
     * @mbggenerated
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device_log.platform
     *
     * @return the value of user_device_log.platform
     *
     * @mbggenerated
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device_log.platform
     *
     * @param platform the value for user_device_log.platform
     *
     * @mbggenerated
     */
    public void setPlatform(String platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device_log.os
     *
     * @return the value of user_device_log.os
     *
     * @mbggenerated
     */
    public String getOs() {
        return os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device_log.os
     *
     * @param os the value for user_device_log.os
     *
     * @mbggenerated
     */
    public void setOs(String os) {
        this.os = os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device_log.device
     *
     * @return the value of user_device_log.device
     *
     * @mbggenerated
     */
    public String getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device_log.device
     *
     * @param device the value for user_device_log.device
     *
     * @mbggenerated
     */
    public void setDevice(String device) {
        this.device = device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device_log.ip
     *
     * @return the value of user_device_log.ip
     *
     * @mbggenerated
     */
    public Long getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device_log.ip
     *
     * @param ip the value for user_device_log.ip
     *
     * @mbggenerated
     */
    public void setIp(Long ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device_log.channel
     *
     * @return the value of user_device_log.channel
     *
     * @mbggenerated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device_log.channel
     *
     * @param channel the value for user_device_log.channel
     *
     * @mbggenerated
     */
    public void setChannel(String channel) {
        this.channel = channel;
    }
}